### ISSUE TITLE
Installation fails without manual intervention on CentOS7

### ISSUE THREAD

**Issue by braddeicide** [Katello/puppet-qpid#46]
qpid-tools installs compat-qpid-cpp-client which then conflicts/blocks qpid-cpp-server and qpid-cpp-client.

Error: Execution of '/bin/yum -d 0 -e 0 -y install qpid-cpp-server' returned 1: Error: compat-qpid-cpp-client conflicts with qpid-cpp-client-1.35.0-1.el7.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
Error: /Stage[main]/Qpid::Install/Package[qpid-cpp-server]/ensure: change from purged to present failed: Execution of '/bin/yum -d 0 -e 0 -y install qpid-cpp-server' returned 1: Error: compat-qpid-cpp-client conflicts with qpid-cpp-client-1.35.0-1.el7.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
Error: Execution of '/bin/yum -d 0 -e 0 -y install qpid-cpp-client' returned 1: Error: compat-qpid-cpp-client conflicts with qpid-cpp-client-1.35.0-1.el7.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
Error: /Stage[main]/Qpid::Install/Package[qpid-cpp-client]/ensure: change from purged to present failed: Execution of '/bin/yum -d 0 -e 0 -y install qpid-cpp-client' returned 1: Error: compat-qpid-cpp-client conflicts with qpid-cpp-client-1.35.0-1.el7.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
Error: Execution of '/bin/yum -d 0 -e 0 -y install qpid-cpp-server-linearstore' returned 1: Error: compat-qpid-cpp-client conflicts with qpid-cpp-client-1.35.0-1.el7.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
Error: /Stage[main]/Qpid::Install/Package[qpid-cpp-server-linearstore]/ensure: change from purged to present failed: Execution of '/bin/yum -d 0 -e 0 -y install qpid-cpp-server-linearstore' returned 1: Error: compat-qpid-cpp-client conflicts with qpid-cpp-client-1.35.0-1.el7.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by stbenjam** [comment]
Did you have compat-qpid-cpp-client already installed before hand? What repos did you have enabled when you get the error?

**Comment by rgarrigue** [comment]
Hi

I've the same issue. It comes from

```
class qpid::install {

  include ::qpid::tools

  package { $qpid::server_packages:
    ensure => $qpid::version,
    before => Service['qpidd'],
  }
```

::qpid::tools install qpid-tools rpm installation, which include compat-qpid-cpp-client dependency, which is incompatible with qpid-cpp-client, which is part of $qpid::server_packages.

Tried some require, priority & so on, no solution to keep tools in.

**Comment by ekohl** [comment]
I can confirm that I can reproduce it and installing qpid-cpp-client before qpid-tools fixes it. The most minimal workaround:
```puppet
Package['qpid-cpp-client'] -> Package['qpid-tools']
```

**Comment by rgarrigue** [comment]
I ended up with this line to kill a couple of annoying stuff at once

    Selinux::Boolean <| |> -> Yumrepo <| |> -> Exec['yum-cache'] -> Package <| |>

**Comment by ekohl** [comment]
But that doesn't solve this particular case where you need 2 packages to be installed in a certain order.

**Comment by rgarrigue** [comment]
It does for me because I also have this

```
yumrepo { 'epel':
      exclude => 'compat-qpid*',
    }
```
