### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by alexjfisher** [Katello/puppet-qpid#72]
The changelog hasn't been updated in the past 3 years.
I'm probably a bit unusual in that I use pulp outside of katello but still use the katello puppet modules.  It'd be nice to at least document the breaking changes between releases.

**Comment by ekohl** [comment]
To me the use outside of the Katello project is a good thing and something I want to encourage. I'll look into generating changelogs like Voxpupuli does.

**Comment by ekohl** [comment]
Due to https://github.com/skywinder/github-changelog-generator/issues/497 we can't automatically generate the changelog but I'll see if I can use it as a base since we don't have that many releases.
